import { useState } from "react";
import Layout from "../components/Layout"
import { useRouter } from "next/router";
import Menu from "../components/Menu";
import {client} from "../lib/client";
import css from "../styles/List.module.css"
import Head from "next/head";
import favicon from "./favicon.ico"
export default function List({ub}) {
    const router = useRouter();
    return (
        <Layout>
          <Head>
          <title>Under Belly</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" type="image/x-icon" href={favicon.src} />
        </Head>
            <div className={css.container}>
                <Menu ub={ub}/>
            </div>
        </Layout>
    );
}
export const getServerSideProps =async()=>
{
  const query='*[_type == "underbelly"]'
  const ub =await client.fetch(query)
  return{
    props:{ub}
  }
}