import Layout from "../components/Layout";
import OrderModal from "../components/OrderModal";
import Head from "next/head";
import favicon from "./favicon.ico"
export default function Success()
{
    return(
        <Layout>
            <Head>
          <title>Under Belly</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" type="image/x-icon" href={favicon.src} />
        </Head>
            <OrderModal opened={true} PaymentMethod={1}/>
        </Layout>
    )
}